### ISSUE TITLE
`group` functions using `NonEmpty`

### ISSUE THREAD

**Issue by sjakobi** [ndmitchell/extra#13]
I've now found myself several times using the following function:

```
collect :: Ord k => [(k, v)] -> [(k, NonEmpty v)]
collect = map (second NonEmpty.fromList) . groupSort
```

Having the type tell you that the value lists are non-empty often turns out to be very handy.

Would you be interested in including such a function and possibly similar variants for `groupSortOn` and `groupSortBy`?

I'm not sure about the naming so far. Would there be a point in deprecating the existing group functions in `Data.List.Extra` in favor of improved versions in `Data.List.NonEmpty.Extra`?

`semigroups` (and soon `base`!) contains [a few more group variants](http://haddock.stackage.org/lts-5.14/semigroups-0.18.1/Data-List-NonEmpty.html#g:5) that might serve as inspiration…

**Comment by ndmitchell** [comment]
`NonEmpty` is not in `base` for all the GHC versions I support, which is back to 7.4, making such code tricky to integrate into `extra`. Even if it were, in general NonEmpty doesn't compose nicely with the existing list related functions - it really requires using the full set of NonEmpty functions from Data.List.NonEmpty, otherwise you throw the invariant away too soon. I also note that Data.List.NonEmpty is full of Group functions (I count 8 already), so perhaps adding groupSort/groupSortBy/groupSortWith to that module/package is a better place for them to live?

**Comment by sjakobi** [comment]
> I also note that Data.List.NonEmpty is full of Group functions (I count 8 already), so perhaps adding groupSort/groupSortBy/groupSortWith to that module/package is a better place for them to live?

Good idea! And thanks for responding so quickly! :+1:
