### ISSUE TITLE
Add mconcatMap and mconcatMapM

### ISSUE THREAD

**Issue by sjakobi** [ndmitchell/extra#14]
I just found myself wishing that `concatMapM` had type `(Monad m, Monoid o) => (a -> m o) -> [a] -> m o` or even `(Foldable f, Monad m, Monoid o) => (a -> m o) -> f a -> m o`.

Many other functions like `firstJust`, `allSame` etc. could get  similar generalizations.

Would it be ok to generalize the existing functions in Data.Monad.Extra and Data.List.Extra in this way? Would there be a point in adding generalized variants instead?

**Comment by ndmitchell** [comment]
I'm generally not a fan of the generalisations - I find them harder to work with and harder to use in practice. See http://neilmitchell.blogspot.co.uk/2014/10/why-traversablefoldable-should-not-be.html for my thoughts, in particular "Why generality hurts". To address your specific instances:

* For `concatMap`, I'm not actually totally against the `Monoid` generalisation there, but the `Foldable` seems to be going too far. Plus, I note the `base` library generalised to `Foldable` but _didn't_ make the `Monoid` generalisation - so that generalisation seems like a bad plan.
* Is `firstJust` not in the Prelude with one of the traversable/foldable generalisations? I don't know where, but I suspect either it to something close is there. That is one of the things I dislike about generalisations :smile:.
* For `allSame` you are basically avoiding one `toList` call, so the benefit is slight at best.

Of course, I realise these are my personal opinions, and someone creating an `extra-general` package with all the generalisations wouldn't seem an unreasonable thing to do.

**Comment by sjakobi** [comment]
These are actually pretty good points! It's interesting to hear your perspective on library design!

Regarding `firstJust`: Yes that's actually `asum` from `Data.Foldable` - I had forgotten about it! :smile:

Maybe a function `mconcatMapM :: (Monad m, Monoid o) => (a -> m o) -> [a] -> m o` would make a useful addition though?

**Comment by ndmitchell** [comment]
Nice spot on `asum`!

Yep, adding `mconcatMapM` seems sensible, provided `mconcatMap` also gets included as well.

The only possible question is whether it should have type `Monad` or `Applicative` as the constraint. I'm completely happy with `Monad` (its consistent) or `Applicative` (if that's powerful enough it's a better definition). I'm also happy replacing the existing `Monad` contexts that are unnecessary with `Applicative`.

**Comment by ndmitchell** [comment]
Done.
