### ISSUE TITLE
Some functions I'm usin

### ISSUE THREAD

**Issue by marcosdumay** [ndmitchell/extra#29]
Those are some functions I've been using a lot in parsers:

    import qualified Control.Category as C
    import Control.Monad
    import Control.Applicative
    
    composeMany :: (Alternative m, C.Category f) => m (f a a) -> m (f a a)
    composeMany f = foldl (C.>>>) C.id <$> many f
    
    ($^) :: (Monad m) => m (a -> a) -> a -> m a
    ($^) f a = f `ap` return a

Where I'm parsing values that may come in any order, I create an initial state and a parser that returns a function updating that state, so I can just call `composeMany parser $^ initialState`. 

Would you mind adding them? I'd think `($^)` goes into Control.Monad.Extra, but I don't know where `composeMany` would go. If you want them, I can add docs and prepare a PR.

**Comment by ndmitchell** [comment]
While `composeMany` might be useful in certain situations, it doesn't seem a good fit for extra - there's nothing quite like it already, and nothing that even depends on alternative or category. In addition, I have almost no intuition of what it does.

For the second, I think you can generalise from `Monad` to `Applicative`, and generalise from `a -> a` to `a -> b`. Once you've done that you end up with something like `liftA` but the other way around, or even the dual of `fmap` in some sense. For that, I'd be curious to know what the operator should be called - I don't think `$^` is necessarily the right intuition. FWIW, I have defined this function before, several times, but I tend to define a family of operators, which are the types:

```
Applicative m => m (a -> b) -> a -> m b
Applicative m => (a -> b) -> m a -> m b
Applicative m => m (a -> b) -> m a -> m b
```

The last two are `<$>` and `<*>`, but I define them with names like `^$` and `^$^` to have full symmetry. That said, because they don't fit in with the existing operators, I've never been a fan.

**Comment by marcosdumay** [comment]
On a second thought, I should have though `composeMany` for `Monoid` instead of `Category` anyway. It would be much easier to deal with.

I see your point about the operator. I'm left wondering if the `^$` set isn't better than the current `<$>` set, but yes, it's not something anybody would want to change now. On the `<$>` set, the `$>` operator seems to be unused, but because of the way `<$` is defined, it may not be a good choice.

Well, I don't think I have anything valuable to add on this subject anymore. Thanks for the interaction.

**Comment by andreasabel** [comment]
Considering `($^)`, writing `mf <*> pure (a r g)` instead of `mf $^ a r g` does not seem that much extra to write.  Of course with `$^` you can save some parentheses.
Unfortunately, there is no good name available, as `<*` is taken for something else.

**Comment by ndmitchell** [comment]
I disagree about the extra syntactic-overhead of using `pure` - often the code is littered with `$^` in many places, so you go from being mostly about your functions to just having a lot of pure. That said, without a good name, it isn't worth it.
